### ISSUE TITLE
Web App Example

### ISSUE THREAD

**Issue by andreas-stefik** [qorf/quorum-website#10]
Community Request

Quorum reference pages contain many useful and fully functioning Quorum language examples.

Do you have some time line to also add WEB browser Quorum app code example? Quorum reference is really very good idea of your team. Because you are always publish new Quorum libraryes or language features in time.

I will be looking forward to Webbrowser project app example.

**Comment by JanuszChmiel** [comment]
Dear MR Stefik. Thank you very much for your reported issue. You have made very big joy to Me.
I have thought, that if I will compile some of The provided interface based Quorum reference code example as a WEB browser app, that I will simply open default.html and app will be accessible with The screen reader like a WEB app. I have thought, that it will not be necessary to have access to Quorum WEB server. That I will be able to host such apps on static server without Apache, Mysql, ETC. But very probably, it is impossible. It is sad, because Quorum is much more simple than Object Pascal and Pas2JS transpiller. This transpiller generate .js file which can be simply executed with no online external server requirements. Unfortunately, my logical think based brain operations were too weak to understand code logic and object Pascal. So I have been so overjoyed by Quorum. I have thought, that I will be able to store compiled project on some server without setup Quorum server somewhere or with no need to use Quorum server which run thanks to The Quorum code developers.
If it is impossible, I Am very sorry, that I have bothered Quorum mailing list and MR Stefik so much.
I have only wanted to make my dreams to come true.

But even if WEbbrowser app requires connection to Quorum server, please try to provide some example with some interface based app or with WEB pages app if WEB browser app can not create accessible screen reader compatible GUI. There are many libraryes to create WEB pages in Quorum including AUdio tag support, ETC.

**Comment by andreas-stefik** [comment]
You don't need the Quorum server to run the HTML pages, nor do you need apache/mysql, or anything really. To run a Quorum program in HTML, you just have to load the page in a browser. Those pages you make though can do anything, so we can't know what circumstances you have exactly, so it's on you to figure out what you are actually trying to achieve.

The one exception here is fonts. Quorum requires you to host something for fonts, because of web assembly, and this is out of our control. Nginx/apache/any free server on your machine will do. Importantly though, this has nothing to do with the Quorum server itself. You need a "local" server on "your" machine, or to host anywhere you wish.

There might be a workaround for this, but it only matters if you need font loading in your application. That said, downloading and installing one of these servers is free and only takes a short time to setup.

**Comment by JanuszChmiel** [comment]
OK dear MR Stefik. Thank you for your extreme patience. So Theoretically.
Is it possible to build The following sample project as a WEB page, which will be loadable in WEB browser with no need to connect to quorum live or other server? So Theoretically, this app could even work offline in The browser?

https://quorumlanguage.com/tutorials/ui/tree.html
I have fallen in love with special technique, which allow user to run Quorum apps inside WEB browser, because it is cross platform compatible. On Android and Windows 100 % and even with Orca screen reader for Linux.
My goal is to use quorum WEB browser apps for creating memory training test. So Quorum example codes are good starting point to try GUI how does Quorum work and I will rewrite The code in Quorum studio, because it is brilliant piece of programmers team work. Even Google could learn from yours team about how to make commercial and fully accessible IDE. YMr Stefik I can only congratulate to you and all engaged experts.

**Comment by JanuszChmiel** [comment]
Here is Tree example attached. I have compiled it with Quorum studio. I have even tried to repair default.js Javascript file according to The instructions in The attached readme.txt. But Really, empty Browser window with The only Web page title. But no app GUi. Is it possible to add other code in to .html file? 
I have removed all other libraryes, because I believe, that it is only for desktop compiled apps which have been built to .jar format in Quorum studio.
[Run.zip](https://github.com/qorf/quorum-website/files/10428464/Run.zip)

**Comment by andreas-stefik** [comment]
Correct, you can do stuff like this on the web in the latest versions of Quorum. As a reminder, the accessibility architecture for the web is in active development. It works now, but there is more to do. Also, because trees involve fonts, you'll need a local web server on your local machine for everything to work how you expect. 

Also because this doesn't appear to be a bug, I'm going to close this ticket. Feel free to respond more on the mailing list if you have questions.
